### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by benofben** [oracle/oci-quickstart-cloudera#24]
Issue from the field -----

Hope this email finds you well. Apologies for the direct message but I’ve seen that you’ve been committing quite a bit to the oci-quickstart-cloudera repo and I need some help on executing your scripts.
 
IHAC that wants to test OCI for its Cloudera cluster and eventually move from IaaS to PaaS Big Data Service (BDS) on OCI. Since BDS is not available yet and the have tight timelines for evaluating the cloud provider I’ve thought on using you terraform scripts to spin up a cluster and have them try out IaaS with the argument that is the same infrastructure and Hadoop stack they will have on BDS.
 
I’m running into some issues and if you could help/guide me it would be great.
 
So far I’ve created an instance on OCI with the Oracle Developer Image that has already Terraform installed. I’ve cloned your repo according to the instructions (https://github.com/oracle/oci-quickstart-cloudera), got the env-vars.sh, altered the values on the env-vars.sh as well as the shape values on the variables.tf; I’ve pasted the changes I’ve done below. I have the keys generated on the directory specified and already set up on the user the API Key.
 
env-vars.sh
 
#!/bin/sh
 
# Required for the OCI Provider
export TF_VAR_tenancy_ocid="ocid1.tenancy.oc1….."
export TF_VAR_compartment_ocid="ocid1.compartment.oc1….."
export TF_VAR_user_ocid="ocid1.user.oc1….."
export TF_VAR_fingerprint=$(cat ~/.oci/oci_api_key.fingerprint)
export TF_VAR_private_key_path="~/.oci/oci_api_key.pem"
export TF_VAR_region="eu-frankfurt-1"
 
# Keys used to SSH to OCI VMs
export TF_VAR_ssh_public_key=$(cat ~/.oci/oci.pub)
export TF_VAR_ssh_private_key=$(cat ~/.oci/oci)
 
When I execute the terraform plan I got the following error related to authentication.
 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
 
data.oci_identity_availability_domains.ADs: Refreshing state...
data.oci_identity_availability_domains.ADs: Refreshing state...
data.oci_core_services.all_svcs_moniker: Refreshing state...
 
Error: Error refreshing state: 3 error(s) occurred:
 
* data.oci_identity_availability_domains.ADs: 1 error(s) occurred:
 
* data.oci_identity_availability_domains.ADs: data.oci_identity_availability_domains.ADs: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: 50fb08ae8431be899aec2d128e571273/C8CCC68E888003E52EA5C66CCAC37DDE/2B43F0C83DA5DD864D7ADF814DAFD37D
* module.network.data.oci_identity_availability_domains.ADs: 1 error(s) occurred:
 
* module.network.data.oci_identity_availability_domains.ADs: data.oci_identity_availability_domains.ADs: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: c131ca92f56ebf0d15caac671e3dc841/F1CDF261D92206239AE9480E2094C846/4C71C8DE5A2AFC6A959C97BA73283C31
* module.network.data.oci_core_services.all_svcs_moniker: 1 error(s) occurred:
 
* module.network.data.oci_core_services.all_svcs_moniker: data.oci_core_services.all_svcs_moniker: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: 89b8c2e9150eb1676ae47261164101ff/2E1F311933F7CC1DCBCA212096F23AFF/091FE6F8F1B6F6E6C08D4697CFBDFE52
 
I have some urgency on this and hence decided to ping you. Can you please help? Is anything that I’m missing?

**Comment by benofben** [comment]
@smithzc does the Cloudera template work with pre-reqs?  I think the readme probably needs cleanup.

**Comment by benofben** [comment]
I'm also concerned about this section: https://github.com/oracle/oci-quickstart-cloudera#python-deployment-using-cm_client

**Comment by benofben** [comment]
There's no detail after the git clone in the readme.

**Comment by smithzc** [comment]
Yes, this does work with pre-reqs.  I found a minor issue with the network output, likely a result in provider code change, but un-related to this issue.   Made minor fixes and pushed to master - just tested and this deployment works.  The error above is related to authentication:
``` Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401.```

Closing this as it's not an issue with the deployment code.
